// <auto-generated />
using System;
using API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(WeaponListDatabase))]
    [Migration("20251030130958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Core.Models.BaseWeaponCLR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChanceOfFlisFromWoodShaft")
                        .HasColumnType("REAL");

                    b.Property<double>("CritPercentageChange")
                        .HasColumnType("REAL");

                    b.Property<double>("CritPercentageDamage")
                        .HasColumnType("REAL");

                    b.Property<double>("DamageModifier")
                        .HasColumnType("REAL");

                    b.Property<int>("DexReq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Shinyness")
                        .HasColumnType("REAL");

                    b.Property<int>("StrenghtReq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
